version: "3.9"

services:
  app:
    build:
      context: ./ # Dockerfile/URL Path
      dockerfile: Dockerfile
    image: sardonyx30/eom:develop # imageName:tag
    tty: true # == `docker -t`
    stdin_open: true # == `docker -i`
    volumes:
      - ./:/root/code
